// @ts-check

import { randomBytes } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import { step } from "./log.mjs";
import { writeMeta } from "./meta.mjs";
import { requirePort } from "./ports.mjs";

/**
 * @param {import("./meta.mjs").SpinMeta} meta
 */
export async function ensureEnvFiles(meta) {
    step("env files", "write");
    const adminEnvPath = join(meta.worktreePath, "apps/admin/.env.local");
    const webEnvPath = join(meta.worktreePath, "apps/web/.env.local");
    const apiEnvPath = join(meta.worktreePath, "apps/api/.env");

    await writeFile(
        adminEnvPath,
        [
            `# Generated by scripts/spin.mjs for spin "${meta.slug}". Safe to edit; re-running spin overwrites.`,
            `NEXT_PUBLIC_API_BASE_URL=http://localhost:${meta.ports.api}`,
            `NEXT_PUBLIC_SITE_URL=http://localhost:${meta.ports.admin}`,
            `NEXT_PUBLIC_DEFAULT_LOCALE=fa`,
            "",
        ].join("\n"),
    );

    /**
     * Storefront env file. The web app's `getBaseUrl()` (packages/sdk) throws when
     * `NEXT_PUBLIC_API_BASE_URL` is missing, so SSR fails with a 500 on the homepage if we
     * don't write this. Matches the admin shape; only the SITE_URL differs.
     */
    await writeFile(
        webEnvPath,
        [
            `# Generated by scripts/spin.mjs for spin "${meta.slug}". Safe to edit; re-running spin overwrites.`,
            `NEXT_PUBLIC_API_BASE_URL=http://localhost:${meta.ports.api}`,
            `NEXT_PUBLIC_SITE_URL=http://localhost:${meta.ports.web}`,
            `NEXT_PUBLIC_DEFAULT_LOCALE=fa`,
            /**
             * Multi-tenant storefront resolves the shop from the Host. In dev a shop is reached at
             * `<slug>.shops.localhost:${meta.ports.web}` (browsers loop `*.localhost` back to
             * 127.0.0.1), so the root is `shops.localhost` here, not the prod `shops.calibra.app`.
             */
            `NEXT_PUBLIC_SHOPS_ROOT=shops.localhost`,
            `NEXT_PUBLIC_TEMPLATE_KEY=default`,
            "",
        ].join("\n"),
    );

    /**
     * Generate (and persist) the stable per-spin secrets on first start. APP_KEY signs cookies
     * and keeps them valid across stop/start of the same spin (a different spin gets a different
     * key — anything signed by one is rejected by another, the correct security boundary).
     * GLITCHTIP_SECRET_KEY is the Django SECRET_KEY for the per-spin GlitchTip instance.
     * MEILI_MASTER_KEY guards the Meilisearch instance — the api uses it to authenticate.
     */
    let metaChanged = false;
    if (!meta.appKey) {
        meta.appKey = randomBytes(32).toString("hex");
        metaChanged = true;
    }
    if (!meta.glitchtipSecretKey) {
        meta.glitchtipSecretKey = randomBytes(48).toString("hex");
        metaChanged = true;
    }
    if (!meta.meiliMasterKey) {
        meta.meiliMasterKey = randomBytes(32).toString("hex");
        metaChanged = true;
    }
    if (metaChanged) await writeMeta(meta);

    const tempoPort = requirePort(meta, "tempo");
    const meiliPort = requirePort(meta, "meilisearch");

    await writeFile(
        apiEnvPath,
        [
            `# Generated by scripts/spin.mjs for spin "${meta.slug}". Safe to edit; re-running spin overwrites.`,
            `TZ=UTC`,
            `NODE_ENV=development`,
            `PORT=${meta.ports.api}`,
            `HOST=0.0.0.0`,
            `APP_NAME=calibra-api-${meta.slug}`,
            `LOG_LEVEL=info`,
            `APP_KEY=${meta.appKey}`,
            `DB_HOST=localhost`,
            `DB_PORT=${meta.ports.db}`,
            /**
             * Two-role multi-tenancy split (see apps/api/config/database.ts). The db container's
             * superuser stays `calibra` and only `db:bootstrap-roles` uses it; the runtime app
             * connects as `calibra_app` (NOBYPASSRLS, RLS always enforced) and migrations/seeders as
             * `calibra_admin` (BYPASSRLS). `scripts/spin/migrate.mjs` bootstraps the roles before the
             * first migrate.
             */
            `DB_USER=calibra_app`,
            `DB_PASSWORD=calibra_app`,
            `DB_DATABASE=calibra`,
            `DB_ADMIN_USER=calibra_admin`,
            `DB_ADMIN_PASSWORD=calibra_admin`,
            `DB_SUPERUSER_USER=calibra`,
            `DB_SUPERUSER_PASSWORD=calibra`,
            /** Phone-OTP SMS sender — `log` driver writes the code to Pino in dev. */
            `SMS_DRIVER=log`,
            `ALLOWED_ORIGINS=http://localhost:${meta.ports.admin},http://localhost:${meta.ports.web}`,
            /**
             * Mailpit (per-spin). The container is brought up by `ensureContainers()` on
             * `spin start` against the spin's own docker-compose project.
             * `MAIL_NOTIFICATIONS_ENABLED=true` opts the importer/exporter runners into sending
             * operator emails on terminal events.
             */
            `MAIL_FROM_ADDRESS=ops@calibra.local`,
            `MAIL_FROM_NAME=Calibra`,
            `MAIL_NOTIFICATIONS_ENABLED=true`,
            `SMTP_HOST=localhost`,
            `SMTP_PORT=${requirePort(meta, "mailpitSmtp")}`,
            `MAILPIT_WEB_URL=http://localhost:${requirePort(meta, "mailpitWeb")}`,
            /**
             * Redis is per-spin too — no shared bus. `keyPrefix: ${APP_NAME}:` in
             * `config/redis.ts` stays as defence-in-depth, but each spin's containers are
             * already isolated by the docker-compose project name.
             */
            `REDIS_HOST=localhost`,
            `REDIS_PORT=${requirePort(meta, "redis")}`,
            /** Bridge SSE broadcasts across api ↔ queue worker (single-process if `none`). */
            `TRANSMIT_TRANSPORT=redis`,
            /**
             * Limiter + lock backing store. `redis` shares counters across api ↔ queue worker
             * (matches the `redis` connection above); tests override to `memory`. Without this
             * env the boot validator in `start/env.ts` refuses to start.
             */
            `LIMITER_STORE=redis`,
            /**
             * Background-job queue.
             *  - `database`: jobs persisted in Postgres; the spin's `queue:work` process polls.
             *    Transmit's redis transport (config/transmit.ts) bridges broadcasts back to the
             *    api process so the wizard's SSE subscription sees live progress.
             *  - `sync` (set in .env.test only): runs jobs inline; no worker, no transport needed.
             */
            `QUEUE_DRIVER=database`,
            /** Default cache store — selects the multi-tier redis store in `config/cache.ts`. */
            `CACHE_DRIVER=redis`,
            /**
             * Meilisearch. Per-spin instance brought up by docker-compose.meili.yml; the api
             * reaches it on the host (HMR runs the api outside docker). Key is the master key
             * generated above; production overrides to a scoped key minted at deploy time.
             */
            `MEILISEARCH_HOST=http://localhost:${meiliPort}`,
            `MEILISEARCH_API_KEY=${meta.meiliMasterKey}`,
            /**
             * Observability. `DEV_OBSERVABILITY=true` flips the logger transport to also write
             * ndjson into `.spin/logs/api.ndjson` so Promtail can ship it to Loki. The OTLP
             * endpoint points at Tempo's host-published 4318.
             */
            `DEV_OBSERVABILITY=true`,
            `OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:${tempoPort}`,
            `SPIN_API_LOG_PATH=${join(meta.worktreePath, ".spin/logs/api.ndjson")}`,
            /**
             * GlitchTip DSN. Auto-provisioned on first start (best-effort); when the
             * provisioner falls back to manual setup, the line is omitted and Sentry init
             * skips. Operator can paste the DSN here after creating org+project by hand.
             */
            ...(meta.glitchtipDsn ? [`GLITCHTIP_DSN=${meta.glitchtipDsn}`] : []),
            "",
        ].join("\n"),
    );
}
