// @ts-check

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { step } from "./log.mjs";
import { SHARED_CADDY_CA_DIR } from "./paths.mjs";
import { requirePort } from "./ports.mjs";

/**
 * Generate the per-spin config files for Caddy + Prometheus + Promtail + Grafana provisioning.
 * Writes everything into `.spin/config/` under the worktree; the compose files volume-mount
 * those paths read-only. Re-writing on every start is fine — the configs are templated from
 * `meta` and the contents are stable as long as the meta is.
 *
 * Tempo + Loki + Alertmanager use static configs that live in `docker/observability/`
 * (committed) and don't need per-spin templating — they're mounted directly by the compose
 * files. Grafana dashboards live there too.
 *
 * @param {import("./meta.mjs").SpinMeta} meta
 */
export async function ensureObservabilityConfig(meta) {
    step("config", "write observability + caddy");
    const configDir = join(meta.worktreePath, ".spin/config");
    await mkdir(configDir, { recursive: true });
    await mkdir(join(configDir, "grafana/provisioning/datasources"), { recursive: true });
    await mkdir(join(configDir, "grafana/provisioning/dashboards"), { recursive: true });
    await mkdir(join(meta.worktreePath, ".spin/logs"), { recursive: true });
    /**
     * Pre-create the data dirs that Promtail position-file + GlitchTip media volumes need.
     * Without these the bind-mount creates them as root-owned (docker daemon default), which
     * the container processes can't write into.
     */
    await mkdir(join(meta.worktreePath, ".spin/data/promtail"), { recursive: true });

    /**
     * Shared Caddy CA dir. First spin on the host bootstraps the CA into here; every
     * subsequent spin reuses it, which is the whole point — trust once, trust forever.
     * `recursive: true` makes the call a no-op when the dir already exists.
     */
    await mkdir(SHARED_CADDY_CA_DIR, { recursive: true });

    await writeFile(join(configDir, "Caddyfile"), renderCaddyfile(meta));
    await writeFile(join(configDir, "prometheus.yml"), renderPrometheusConfig(meta));
    await writeFile(join(configDir, "promtail.yml"), renderPromtailConfig(meta));
    await writeFile(join(configDir, "grafana/provisioning/datasources/datasources.yml"), renderGrafanaDatasources());
    await writeFile(join(configDir, "grafana/provisioning/dashboards/dashboards.yml"), renderGrafanaDashboardsProvider());
}

/**
 * Render the per-spin Caddyfile. Every observability + dev-ui surface gets a
 * `<service>.<slug>.spin.localhost` hostname with internal-CA TLS. The api / admin / web
 * routes point at `host.docker.internal:<port>` because those processes run on the host
 * (HMR); the rest are container-to-container via service name on the spin's network.
 *
 * @param {import("./meta.mjs").SpinMeta} meta
 */
export function renderCaddyfile(meta) {
    const slug = meta.slug;
    const apiPort = meta.ports.api;
    const adminPort = meta.ports.admin;
    const webPort = meta.ports.web;
    const agentPort = requirePort(meta, "spinAgent");
    return `# Generated by scripts/spin.mjs for spin "${slug}". Re-run \`pnpm spin\` to regenerate.
{
    auto_https disable_redirects
    local_certs
}

${slug}.spin.localhost {
    tls internal
    reverse_proxy host.docker.internal:${agentPort}
}

api.${slug}.spin.localhost {
    tls internal
    reverse_proxy host.docker.internal:${apiPort}
}

admin.${slug}.spin.localhost {
    tls internal
    reverse_proxy host.docker.internal:${adminPort}
}

web.${slug}.spin.localhost {
    tls internal
    reverse_proxy host.docker.internal:${webPort}
}

mail.${slug}.spin.localhost {
    tls internal
    reverse_proxy mailpit:8025
}

redis.${slug}.spin.localhost {
    tls internal
    reverse_proxy redisinsight:5540
}

db.${slug}.spin.localhost {
    tls internal
    reverse_proxy adminer:8080
}

grafana.${slug}.spin.localhost {
    tls internal
    reverse_proxy grafana:3000
}

prom.${slug}.spin.localhost {
    tls internal
    reverse_proxy prometheus:9090
}

loki.${slug}.spin.localhost {
    tls internal
    reverse_proxy loki:3100
}

tempo.${slug}.spin.localhost {
    tls internal
    reverse_proxy tempo:3200
}

alerts.${slug}.spin.localhost {
    tls internal
    reverse_proxy alertmanager:9093
}

errors.${slug}.spin.localhost {
    tls internal
    reverse_proxy glitchtip:8000
}

uptime.${slug}.spin.localhost {
    tls internal
    reverse_proxy uptimekuma:3001
}

search.${slug}.spin.localhost {
    tls internal
    reverse_proxy meilisearch:7700
}
`;
}

/**
 * Render Prometheus's scrape config. The only scrape target is the api on the host (HMR runs
 * outside docker), reached via `host.docker.internal`. Prometheus also scrapes itself so the
 * Prometheus → Grafana wiring has a sanity-check target. Alertmanager is reachable on the
 * compose network but no rules ship in this PR — adding `alertmanagers:` is the hook for
 * future rule authors.
 *
 * @param {import("./meta.mjs").SpinMeta} meta
 */
export function renderPrometheusConfig(meta) {
    return `# Generated by scripts/spin.mjs for spin "${meta.slug}".
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    spin: ${meta.slug}

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Recording + alert rule files are committed under docker/observability/prometheus/rules/ and
# mounted into the prometheus container by the observability compose file. New rule files land
# in that dir and pick up automatically (the wildcard scans on every reload).
rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: calibra-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:${meta.ports.api}
        labels:
          service: calibra-api
          spin: ${meta.slug}
`;
}

/**
 * Render Promtail's pipeline. Reads JSON lines from the api's per-spin ndjson log file
 * (the path is bind-mounted via SPIN_LOG_DIR), parses Pino's standard fields, and ships to
 * Loki with `service=calibra-api` + `spin=<slug>` labels.
 *
 * @param {import("./meta.mjs").SpinMeta} meta
 */
export function renderPromtailConfig(meta) {
    return `# Generated by scripts/spin.mjs for spin "${meta.slug}".
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /run/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: calibra-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: calibra-api
          service: calibra-api
          spin: ${meta.slug}
          __path__: /var/log/api/*.ndjson
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            request_id: request_id
      - labels:
          level:
      - timestamp:
          source: time
          format: UnixMs
`;
}

/**
 * Grafana datasource provisioning — Prometheus, Loki, Tempo. All reach their targets
 * container-to-container by compose service name (not by published host port), so the URLs
 * are identical across spins. Marked `editable: false` so accidental UI tweaks don't drift
 * from the committed config.
 */
export function renderGrafanaDatasources() {
    return `apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
`;
}

/**
 * Grafana dashboard provisioner — points at the dashboards dir we bind-mount from
 * `docker/observability/grafana/dashboards/` (committed JSON, read-only). Auto-imports any
 * `*.json` on boot. New dashboards land in that directory and get picked up automatically.
 */
export function renderGrafanaDashboardsProvider() {
    return `apiVersion: 1

providers:
  - name: calibra
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: false
`;
}
