// @ts-check

import { spawnSync } from "node:child_process";

import { requireSlug } from "./flags.mjs";
import { green, log, step } from "./log.mjs";
import { readMetaOrFail, writeMeta } from "./meta.mjs";
import { requirePort } from "./ports.mjs";
import { run } from "./run.mjs";

/**
 * Open a draft PR for a spin that started life with `--no-pr`, or recreate one that was closed.
 *
 * @param {string[]} args
 */
export async function ensurePr(args) {
    const slug = requireSlug(args[0]);
    const meta = await readMetaOrFail(slug);
    await ensureDraftPrInternal(meta);
    log(green(`  ✓ PR #${meta.prNumber}`));
}

/**
 * @param {import("./meta.mjs").SpinMeta} meta
 */
export async function ensureDraftPrInternal(meta) {
    if (meta.prNumber) {
        step("PR", `exists (#${meta.prNumber})`);
        return;
    }
    /** Need at least one commit on the branch before `gh pr create` will accept it. */
    const hasCommits = spawnSync("git", ["rev-list", "--count", `origin/main..${meta.branch}`], {
        cwd: meta.worktreePath,
        encoding: "utf8",
    });
    const ahead = Number(hasCommits.stdout.trim());
    if (ahead === 0) {
        step("PR", "empty bootstrap commit");
        await run(
            "git",
            [
                "commit",
                "--allow-empty",
                "-m",
                `chore(spin): bootstrap ${meta.slug}\n\nGenerated by \`pnpm spin\`. Replace this commit with real work, or amend it.\n\nPorts: api=${meta.ports.api} admin=${meta.ports.admin} db=${meta.ports.db} pgadmin=${meta.ports.pgadmin}`,
            ],
            { cwd: meta.worktreePath },
        );
    }
    step("PR", "push branch");
    await run("git", ["push", "-u", "origin", meta.branch], { cwd: meta.worktreePath });

    step("PR", "gh pr create --draft");
    const caddyHttps = requirePort(meta, "caddyHttps");
    /**
     * Single link to the spin's homepage. The homepage surfaces every per-service URL,
     * Grafana + Prometheus + Loki deep-links, seed credentials, action buttons, and a live
     * log tail — no need to duplicate any of that into the PR body. Keeps the body short
     * enough that the human-authored Summary / Implementation sections (added later) aren't
     * buried under boilerplate.
     */
    const body = [
        `Bootstrapped by \`pnpm spin ${meta.slug}\`.`,
        ``,
        `**Spin dashboard:** https://${meta.slug}.spin.localhost:${caddyHttps}/`,
        ``,
        `<sub>Teardown: \`pnpm spin stop ${meta.slug}\` · containers + processes only. Add \`--purge --remove\` to wipe everything.</sub>`,
    ].join("\n");
    const result = spawnSync(
        "gh",
        ["pr", "create", "--draft", "--base", "main", "--head", meta.branch, "--title", `spin/${meta.slug}: WIP`, "--body", body],
        { cwd: meta.worktreePath, encoding: "utf8" },
    );
    if (result.status !== 0) {
        throw new Error(`gh pr create failed: ${result.stderr || result.stdout}`);
    }
    const url = result.stdout.trim().split("\n").pop() ?? "";
    const numberMatch = url.match(/\/pull\/(\d+)/);
    meta.prNumber = numberMatch ? Number(numberMatch[1]) : null;
    meta.prUrl = url;
    await writeMeta(meta);
}
