// @ts-check

import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

import { ensureContainers } from "../compose.mjs";
import { ensureEnvFiles } from "../env-files.mjs";
import { LOCAL_SLUG, parseFlags } from "../flags.mjs";
import { printHandoffCard } from "../handoff.mjs";
import { ensureInstall, ensureSdkBuild } from "../install.mjs";
import { cyan, log } from "../log.mjs";
import { loadOrInitLocalMeta } from "../meta.mjs";
import { ensureMigrationsAndSeed } from "../migrate.mjs";
import { ensureObservabilityConfig } from "../observability-config.mjs";
import { startServers, waitForServersReady } from "../processes.mjs";

import { doctor } from "./doctor.mjs";
import { stop } from "./stop.mjs";

/**
 * `pnpm spin local [<sub>]` — bring up the full prod-parity stack against the **current
 * checkout**, without creating a worktree, branch, or PR. Designed for two use-cases:
 *
 *   1. Operators who want the full stack (observability + caddy + meilisearch + glitchtip
 *      + db + redis + mailpit + adminer) without the worktree/PR ceremony.
 *   2. **Agents** investigating a bug or shipping a hotfix on a branch they're already on —
 *      no slug to invent, no PR side-effect, no port-block surprises.
 *
 * The slug is hard-coded to {@link LOCAL_SLUG} so one machine can have at most one in-place
 * spin running. State, ports, and the agent's dashboard work the same as a worktree-based
 * spin (`https://local.spin.localhost:<caddyHttps>`), and `pnpm spin local stop --purge` is
 * the matching teardown.
 *
 * **Guardrail:** if `apps/api/.env` already exists and was NOT generated by spin (no header
 * line), we refuse to start so we don't clobber operator customizations. Move/delete it
 * first, or accept that spin will own the file.
 *
 * @param {string[]} args
 */
export async function local(args) {
    const sub = args[0] ?? "start";
    if (sub === "start" || sub === "up" || sub === "bootstrap") {
        await localStart(args.slice(1));
    } else if (sub === "stop" || sub === "down") {
        await stop([LOCAL_SLUG, ...args.slice(1)]);
    } else if (sub === "status" || sub === "doctor") {
        await doctor([LOCAL_SLUG, ...args.slice(1)]);
    } else {
        /** Default: no subcommand means "start". `pnpm spin local --with-web` is valid. */
        await localStart(args);
    }
}

/**
 * @param {string[]} flagArgs
 */
export async function localStart(flagArgs) {
    const flags = parseFlags(flagArgs);
    const meta = await loadOrInitLocalMeta();
    const apiEnvPath = join(meta.worktreePath, "apps/api/.env");
    if (existsSync(apiEnvPath)) {
        const head = (await readFile(apiEnvPath, "utf8")).split("\n", 1)[0];
        if (!head.includes("Generated by scripts/spin.mjs")) {
            throw new Error(
                [
                    `apps/api/.env exists and was not generated by spin (no header line).`,
                    `Move it aside (\`mv apps/api/.env apps/api/.env.before-spin\`) or delete it, then re-run.`,
                    `spin owns the .env when it provisions a stack — overwriting your custom values silently would be a footgun.`,
                ].join("\n  "),
            );
        }
    }

    log(cyan("spin local"));
    log(`  mode     in-place (no worktree, no branch, no PR)`);
    log(`  cwd      ${meta.worktreePath}`);
    log(`  branch   ${meta.branch}`);
    log(`  ports    api=${meta.ports.api} admin=${meta.ports.admin} db=${meta.ports.db}`);
    log("");

    /** Skip ensureWorktree (we're already in the repo) and ensureDraftPr (no PR by design). */
    await ensureEnvFiles(meta);
    await ensureObservabilityConfig(meta);
    await ensureContainers(meta);
    await ensureInstall(meta);
    await ensureSdkBuild(meta);
    await ensureMigrationsAndSeed(meta);
    await startServers(meta, { withWeb: flags.withWeb });
    await waitForServersReady(meta, { withWeb: flags.withWeb });

    printHandoffCard(meta, { withWeb: flags.withWeb });
}
