/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class MediaSchema extends BaseModel {
  static $columns = ['alt', 'attributes', 'createdAt', 'height', 'id', 'kind', 'mime', 'sizeBytes', 'updatedAt', 'url', 'width'] as const
  $columns = MediaSchema.$columns
  @column()
  declare alt: string | null
  @column()
  declare attributes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare kind: string
  @column()
  declare mime: string | null
  @column()
  declare sizeBytes: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare url: string
  @column()
  declare width: number | null
}

export class PaymentGatewaySchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'enabled', 'id', 'ordering', 'settings', 'supports', 'updatedAt'] as const
  $columns = PaymentGatewaySchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ordering: number
  @column()
  declare settings: any
  @column()
  declare supports: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RegionTranslationSchema extends BaseModel {
  static $columns = ['createdAt', 'locale', 'name', 'regionId', 'updatedAt'] as const
  $columns = RegionTranslationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare locale: string
  @column()
  declare name: string
  @column({ isPrimary: true })
  declare regionId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RegionSchema extends BaseModel {
  static $columns = ['attributes', 'code', 'countryCode', 'createdAt', 'id', 'ordering', 'parentId', 'updatedAt'] as const
  $columns = RegionSchema.$columns
  @column()
  declare attributes: any
  @column()
  declare code: string
  @column()
  declare countryCode: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ordering: number
  @column()
  declare parentId: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'groupKey', 'key', 'type', 'updatedAt', 'value'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare groupKey: string
  @column()
  declare key: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: any
}

export class ShippingMethodSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'descriptionDefault', 'id', 'settingsSchema', 'titleDefault', 'updatedAt'] as const
  $columns = ShippingMethodSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descriptionDefault: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare settingsSchema: any
  @column()
  declare titleDefault: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ShippingZoneLocationSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'type', 'updatedAt', 'zoneId'] as const
  $columns = ShippingZoneLocationSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare zoneId: bigint | number
}

export class ShippingZoneMethodSchema extends BaseModel {
  static $columns = ['createdAt', 'enabled', 'id', 'methodId', 'ordering', 'settings', 'titleOverride', 'updatedAt', 'zoneId'] as const
  $columns = ShippingZoneMethodSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare methodId: bigint | number
  @column()
  declare ordering: number
  @column()
  declare settings: any
  @column()
  declare titleOverride: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare zoneId: bigint | number
}

export class ShippingZoneSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isFallback', 'name', 'updatedAt'] as const
  $columns = ShippingZoneSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isFallback: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaxClassSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = TaxClassSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaxRateSchema extends BaseModel {
  static $columns = ['appliesToShipping', 'cities', 'compound', 'country', 'createdAt', 'id', 'label', 'ordering', 'postcodes', 'priority', 'rate', 'regionId', 'taxClassId', 'updatedAt'] as const
  $columns = TaxRateSchema.$columns
  @column()
  declare appliesToShipping: boolean
  @column()
  declare cities: any | null
  @column()
  declare compound: boolean
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare label: string
  @column()
  declare ordering: number
  @column()
  declare postcodes: any | null
  @column()
  declare priority: number
  @column()
  declare rate: string
  @column()
  declare regionId: bigint | number | null
  @column()
  declare taxClassId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
